---
title: "canopy_soil_distribution_map"
author: "Ethan Abercrombie"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
require(sf)
require(tidyverse)
require(rnaturalearth)
require(raster) #loads GADM data
require(elevatr) #elevation data
require(maps)
require(rmapshaper) #remove islands (ms_filter_islands)
require(GADMTools) #union
require(maps) #map_data()

#Quickplot function
quick_plot <- function(plot_export_folder = '/Users/ethanabercrombie/Desktop/', file_name = 'test', plot_object){
    quartz(type = 'pdf',
         dpi = 144,
         antialias = T,
         file = paste0(plot_export_folder,
                       file_name))
  
  print(plot_object)
  
  graphics.off()
  
# path = paste0(plot_export_folder,
#                 file_name,
#                 '.pdf')
# system2('open', args = c('-a Preview.app',path), wait = FALSE)
}
```

Clean article data.

```{r}
article_data <- read_csv('~/Desktop/Canopy_Soils_Review/Systematic Search_latlong.csv')

article_data <- article_data[1:117,] %>% 
  rename('study_site_country' = "study site country",
         'first_author_country' = "first author country") %>% 
  mutate(Latitude = as.numeric(Latitude),
         Longitude = as.numeric(Longitude)) %>% 
  mutate(Longitude = if_else(Longitude > 0 & study_site_country == 'Costa Rica',
                             Longitude*-1,
                             Longitude)) %>% 
  filter(Latitude != "NA" &
           Longitude != "NA")

article_data_sf <- st_as_sf(x = article_data,
                            coords = c(x = 'Longitude',
                                       y = 'Latitude'),
                            crs = 4326,
                            remove = FALSE)
```

```{r}
#Load spatial data.

#world_data
continents <- c('North America',
                'South America',
                'Europe',
                'Asia',
                'Africa',
                'Oceania')
world_data <- st_as_sf(ne_countries(continent = continents))

#costa_rica
cr_0_data <- ms_filter_islands(
  st_as_sf(
    getData(path = '~/Desktop/Spatial_Data/',
                     country = 'CRI',
                     level = 0)
  ),
  min_area = 10^8
)

cr_1_data <- ms_filter_islands(
  st_as_sf(
    getData(path = '~/Desktop/Spatial_Data/',
                     country = 'CRI',
                     level = 1)
  ),
  min_area = 10^8
)
```


```{r}
#Elevation data

world_elevation <- get_elev_raster(locations = world_data,
                                z = 0,
                                clip = 'locations')
world_elevation <- as.data.frame(world_elevation,
                                 xy = T)
colnames(world_elevation)[3] = "elevation"
world_elevation <- world_elevation[complete.cases(world_elevation),]

##Costa Rica
cr_elevation <- get_elev_raster(locations = cr_0_data,
                                z = 9,
                                clip = 'locations')
cr_elevation <- as.data.frame(cr_elevation,
                              xy = T)
colnames(cr_elevation)[3] = "elevation"
cr_elevation <- cr_elevation[complete.cases(cr_elevation),]
```

```{r}
world_map <- ggplot() +
  geom_sf(data = world_data) +
  geom_sf(data = article_data_sf) +
  geom_raster(data = world_elevation,
            aes(x = x,
                y = y,
                fill = elevation)) +
  theme(panel.background = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank())
quick_plot(plot_object = world_map)

cr_map <- ggplot() +
  geom_sf(data = cr_0_data,
          color = 'white') +
  geom_raster(data = cr_elevation,
            aes(x = x,
                y = y,
                fill = elevation)) +
  geom_sf(data = cr_1_data,
          color = 'light gray',
          fill = NA) +
  geom_sf(data = st_jitter(filter(article_data_sf,
                           study_site_country == 'Costa Rica'),
                           amount = 0.05),
          color = "white",
          alpha = 0.3,
          size = 2.5,
          inherit.aes = F) +
  scale_fill_viridis_c()
quick_plot(plot_object = cr_map)
```
